#!/usr/bin/env bash

#
#  Copyright 2019 The OpenThread Authors
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

set -e +o pipefail

readonly SIZE_REPORT_FILE=/tmp/size_report

size_report_init()
{
    if [[ "${GITHUB_WORKFLOW}" ]]; then
      # pattern of GITHUB_REF: refs/pull/:prNumber/merge
      local number=$(cut -d/ -f3 <<< "${GITHUB_REF}")
      local commit_id="${GITHUB_SHA}"
      local base_branch="${OT_BASE_BRANCH}"
      local repo_slugs=(${GITHUB_REPOSITORY//\// })
    else
      local number="${TRAVIS_PULL_REQUEST}"
      local commit_id="${TRAVIS_PULL_REQUEST_SHA}"
      local base_branch="${TRAVIS_BRANCH}"
      local repo_slugs=(${TRAVIS_REPO_SLUG//\// })
    fi

    cat > "${SIZE_REPORT_FILE}" <<EOF
{
  "name": "$1",
  "number": "${number}",
  "commit_id": "${pull_request_sha}",
  "base_commit_id": "${OT_MERGE_BASE_SHA}",
  "base_branch": "${base_branch}",
  "owner": "${repo_slugs[0]}",
  "repo": "${repo_slugs[1]}",
  "data": [{
EOF
}

size_report_size()
{
    name="$(basename $1)"

    [[ "${name}" = "$(basename $2)" ]] || return

    cat >> "${SIZE_REPORT_FILE}" <<EOF
    "name": "$name",
    "type": "size",
    "base": [$(size "$1" | awk '{text+=$1} {bss+=$2} {data+=$3} {total+=$4} END {printf "%d,%d,%d,%d", text, bss, data, total}')],
    "pr": [$(size "$2" | awk '{text+=$1} {bss+=$2} {data+=$3} {total+=$4} END {printf "%d,%d,%d,%d", text, bss, data, total}')]
  },{
EOF
}

size_report_post()
{
    echo -e "  }]\n}" >> "${SIZE_REPORT_FILE}"
    curl -X POST \
        -H "Content-Type: application/json" \
        -d @"${SIZE_REPORT_FILE}" \
        "${SIZE_REPORT_URL}/review"
}

main()
{
    case $1 in
        init)
            shift
            size_report_init "$@"
            ;;

        size)
            shift
            size_report_size "$@"
            ;;

        post)
            size_report_post
            ;;
    esac
}

main "$@"
